runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static
- url: /images
  static_files: static/images.html
  upload: static/images.html
- url: /.*
  script: main.app
