runtime: python27
threadsafe: true
api_version: 1
service: backend

builtins:
- remote_api: on

handlers:
- url: /_ah/api/.*
  script: main.api
- url: /cron/.*
  script: cron.app
  login: admin

libraries:
- name: pycrypto
  version: 2.6
- name: ssl
  version: 2.7.11

env_variables:
  ENDPOINTS_SERVICE_NAME: backend-dot-youtube-manager-196811.appspot.com
  ENDPOINTS_SERVICE_VERSION: 2018-05-11r0
